name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/FsExcel
    - name: Build
      run: dotnet build --no-restore src/FsExcel
    - name: Test
      run: dotnet test --no-build --verbosity normal src/FsExcel
    - name: Publish FsExcel
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/FsExcel/FsExcel.fsproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}      
